---
driver:
  name: vagrant
  driver_config:
  require_chef_omnibus: true
  use_vagrant_berkshelf_plugin: true
  customize:
    memory: 2048
    cpus: 1

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: canonical-ubuntu-12.04
      box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[jboss]
    attributes:
      java:
        jdk_version: "7"
        install_flavor: "oracle"
        oracle: 
          accept_oracle_download_terms: true
 
